doug-wade/tybalt

packages/esbuild-plugin/package.json, packages/eslint-plugin/package.json
Removes private fields on packages used by the tybalt cli
=> chore: remove private fields on cli packages

packages/test-utils/package.json
=> fix test-utils export

package.json, packages/cli/package.json, packages/core/package.json, packages/eleventy-plugin-vanilla-example/package.json, packages/eleventy-plugin/package.json, packages/esbuild-plugin/package.json, packages/eslint-plugin/package.json, packages/example/package.json, packages/test-utils-lit-example/package.json, packages/test-utils/package.json, packages/validator/package.json, packages/website/package.json, yarn.lock
=> bump version to 0.0.3

.github/workflows/conventional-commit.yaml, .github/workflows/coverage.yaml, .github/workflows/gh-pages.yaml
=> fix(#108): upgrade to actions/checkout@v3

package.json, packages/cli/jest.config.js, packages/cli/jest.setup.js, packages/example/jest.config.js, packages/example/jest.setup.js, packages/test-utils-lit-example/jest.config.js, packages/test-utils-lit-example/jest.setup.js, packages/test-utils/jest.config.js, packages/test-utils/jest.setup.js, packages/test-utils/package.json, yarn.lock
=> fix(#110): remove unneeded devDependencies from root package.json

CONTRIBUTING.md, package.json, turbo.json
=> fix(#22): add top-level serve command

CONTRIBUTING.md, packages/website/index.html
=> fix(#100): add discord server

packages/core/src/api/define-component.ts, packages/example/src/Button/button.component.ts, packages/example/src/Link/link.component.ts, packages/example/src/index.html, packages/test-utils/src/util/base-wrapper.ts
=> fix(#115): fix links missing text

CODE_OF_CONDUCT.md
=> fix(#124): Add a code of conduct

package.json, packages/cli/package.json, packages/core/package.json, packages/eleventy-plugin-vanilla-example/package.json, packages/eleventy-plugin/package.json, packages/esbuild-plugin/package.json, packages/eslint-plugin/package.json, packages/example/package.json, packages/test-utils/package.json, packages/validator/package.json, packages/website/package.json
=> chore: update to 0.0.8

.github/dependabot.yml
=> fix(#133): Add prefix to dependabot commit message

.github/workflows/conventional-commit.yaml, .github/workflows/gh-pages.yaml, .github/workflows/npm-publish.yml, .github/workflows/yarn-test.yaml
=> feat(#122): Publish to Discord when deploying

.vscode/launch.json
=> feat(#116): Add launch.json

packages/website/.eleventy.js
=> feat(#114): Open website in browser when running serve

packages/cli/src/commands/build.ts, packages/cli/src/tybalt-esbuild-plugin.d.ts, packages/esbuild-plugin/index.js, packages/esbuild-plugin/package.json, packages/esbuild-plugin/src/index.ts, packages/esbuild-plugin/tsconfig.json, packages/example/package.json, packages/example/src/Circle/circle.component.ts, packages/example/src/Circle/circle.css, packages/example/src/index.html, packages/example/src/index.ts, yarn.lock
=> feat(#42): Support importing css from file

packages/core/tst/integration/component-rendering.test.ts, packages/test-utils/src/types.d.ts, packages/test-utils/src/util/base-wrapper.ts, packages/test-utils/src/util/empty-wrapper.ts, packages/test-utils/src/util/wrapper-array.ts
adds a test that demonstratest #62 is complete
=> fix(#62): Add re-render integration test

packages/core/src/api/define-component.ts, packages/core/src/types.d.ts, packages/core/tst/api/define-component.test.ts, packages/core/tst/integration/component-rendering.test.ts, packages/eslint-plugin/jest.config.js, packages/example/__mocks__/style-mock.ts, packages/example/jest.config.js, packages/example/src/Button/button.component.ts, packages/example/src/Button/button.css, packages/example/src/Button/button.test.ts, packages/example/src/Circle/circle.component.ts, packages/website/pages/core.md, packages/website/pages/test-utils.md
=> fix(#121): support derived state

packages/esbuild-plugin/README.md, packages/website/components/sidebar.js, packages/website/pages/eleventy-plugin.md, packages/website/pages/esbuild-plugin.md
Add a new page to the website for the esbuild plugin
=> feat(#197): Add esbuild page to website

packages/validator/src/api/integer.ts, packages/validator/src/api/number.ts, packages/validator/tst/api/integer.test.ts, packages/validator/tst/api/number.test.ts
Adds an integer and number validator
=> fix(#203): Add number validator

packages/validator/src/index.ts, packages/website/pages/eleventy-plugin.md, packages/website/pages/esbuild-plugin.md, packages/website/pages/validator.md
adds some h1s and doc blocks for integer and number
=> chore: minor website fixes

packages/core/README.md
=> Change "cli" to "core"

CNAME
See if this fixes our DNS issues.
=> fix(#356): Create CNAME

packages/website/components/sidebar.js
=> feat: Update sidebar.js

CONTRIBUTING.md, MAINTAINING.md
=> docs: Add maintaining.md

packages/website/pages/new-website-guide.md, packages/website/pages/writing-tests-guide.md, packages/website/pages/writing-unit-tests-guide.md
Adds two more guides and fixes #349
=> Add guides

packages/website/index.html
Addresses #407 and #409, which asks for a meta description and a language specifier for search-engine optimisation.
Thanks for this easy first issue ❤️
=> Add a meta description for better SEO

package.json, packages/cli/package.json, packages/cli/src/index.ts, packages/cli/tst/index.test.ts, yarn.lock
=> fix(#411): Remove dependency ts-node-esm

packages/core/src/api/define-component.ts, packages/core/src/types.d.ts
=> fix(#421): Remove eslint ignore in @tybalt/core types.d.ts

README.md
Fixes #366 
This should add a version badge to the README.
=> chore(#366): Added version badge

.github/workflows/coverage.yaml, package.json, yarn.lock
=> fix(#368): We'll get more coverage if we create the combined-coverage file

package.json, packages/validator/src/api/array.ts, packages/validator/src/index.ts, packages/website/pages/validator.md
=> fix(#453): Include array in built output

.github/workflows/coverage.yaml, .github/workflows/yarn-test.yaml, package.json, packages/cli/package.json, packages/core/package.json, packages/eslint-plugin/package.json, packages/example/package.json, packages/parser/package.json, packages/test-utils-lit-example/package.json, packages/test-utils/package.json, turbo.json
We're missing some packages -- I think this'll get more
=> fix: include more coverage in ci report

package.json, packages/cli/package.json, packages/core/package.json, packages/eleventy-plugin-vanilla-example/package.json, packages/eleventy-plugin/package.json, packages/esbuild-plugin/package.json, packages/eslint-plugin/package.json, packages/example/package.json, packages/test-utils/package.json, packages/validator/package.json, packages/website/package.json
=> chore: go to v0.0.20

packages/core/src/api/define-component.ts, packages/example/src/ClosedShadowDom/ClosedShadowDom.component.ts, packages/example/src/index.html, packages/example/src/index.ts
=> fix(#470): Support closed dom

packages/core/src/api/context-event.ts, packages/core/src/api/define-component.ts, packages/core/src/types.d.ts, packages/core/tst/integration/contexts.test.ts
=> feat(#447): Add tests for contexts

package.json, packages/cli/package.json, packages/core/package.json, packages/eleventy-plugin-vanilla-example/package.json, packages/eleventy-plugin/package.json, packages/esbuild-plugin/package.json, packages/eslint-plugin/package.json, packages/example/package.json, packages/test-utils/package.json, packages/validator/package.json, packages/website/package.json
=> chore(NOBUG): Go to v0.0.21

packages/validator/src/api/compose.ts, packages/validator/tst/api/compose.test.ts, packages/website/pages/data-fetching-guide.md, packages/website/pages/parser.md, packages/website/pages/validator.md
Also includes some documentation updates from mistakes I found while working on https://github.com/doug-wade/dougwade.io/pull/43
=> feat(NOBUG): Filter null validators in compose

packages/core/src/api/define-component.ts
=> Revert "fix(NOBUG): Fix some troubles with inputs"

packages/website/built-with-tybalt.html, packages/website/components/project-card/project-card.component.ts, packages/website/components/sidebar/sidebar.component.ts, packages/website/components/sidebar/sidebar.test.ts, packages/website/css/base.css, packages/website/package.json
=> fix(#385): Add built-with-tybalt page

packages/website/components/code-example/code-example.component.ts, packages/website/components/main/main.component.ts
=> fix(#554): fix code samples on homepage

packages/eslint-plugin/package.json
=> fix(#586): fix cannot find module error

packages/eslint-plugin/package.json
=> fix(#584): add files key to package.json

packages/cli/src/commands/scaffold.ts
=> fix(#512): fix invalid package.json error

packages/eleventy-plugin-vanilla-example/.eleventy.js, packages/esbuild-plugin/src/index.ts
=> fix(NOBUG): remove stray deprecated argument

packages/core/src/api/define-component.ts, packages/core/tst/integration/component-rendering.test.ts
=> feat(#602): Support multi-word prop names

.github/workflows/cypress.yaml, .gitignore, packages/website/_data/sentry.js, packages/website/_includes/layout.html, packages/website/built-with-tybalt.html, packages/website/index.html, packages/website/package.json, yarn.lock
=> Migrate from ga to sentry

packages/website/_includes/layout.html, packages/website/built-with-tybalt.html, packages/website/index.html
=> fix(#649): Guard Sentry calls

package.json, packages/cli/package.json, packages/context/package.json, packages/core/package.json, packages/cypress/package.json, packages/eleventy-plugin-vanilla-example/package.json, packages/eleventy-plugin/package.json, packages/esbuild-plugin/package.json, packages/eslint-plugin/package.json, packages/example/package.json, packages/parser/package.json, packages/reactive/package.json, packages/test-utils-lit-example/package.json, packages/test-utils/package.json, packages/validator/package.json, packages/website/package.json, yarn.lock
Bump the patch version to pick up dependency updates.
=> chore(NOBUG): Go to version v0.1.10
